#!/usr/bin/env python3
"""Regenerate the restricted-texts block of .gitignore from the registry.

data/restricted_texts.json names texts that must never reach the public
repository. This script turns that list into ignore rules and writes them
between the marker comments in .gitignore, replacing whatever was there
before. Run it after adding, removing, or renaming a registry entry:

    venv/bin/python scripts/corpus/restricted_texts_gitignore.py [--root PATH]

For each registry id it emits two lines, whole file and book parts, under
every language directory where a matching file actually exists on this
checkout:

    texts/<lang>/<id>.tess
    texts/<lang>/<id>.part.*.tess

A restricted text that has not yet arrived on this checkout (the normal case
in the public repository, which never holds one) contributes no lines yet --
there is nothing on disk to name. The rule is still a reminder for whoever
adds the file: the registry entry exists, so re-running this script once the
file lands produces the line that protects it.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))

from backend.restricted_texts import load  # noqa: E402
from backend.work_names import base_work  # noqa: E402

BEGIN = '# BEGIN restricted texts (generated by scripts/corpus/restricted_texts_gitignore.py)'
END = '# END restricted texts'

# The language directories .gitignore un-ignores (see the comment above
# `texts/*` there). A restricted text can only ever live in one of these.
LANGUAGES = ['la', 'grc', 'en', 'cop', 'he', 'it', 'gmh', 'fro']


def build_lines(root):
    """The ignore lines for every registry id actually present on disk,
    plus a one-line note for each id not yet present (nothing to ignore,
    but a record that the registry expects it)."""
    registry = load()
    lines = []
    present = set()
    for lang in LANGUAGES:
        lang_dir = os.path.join(root, 'texts', lang)
        if not os.path.isdir(lang_dir):
            continue
        for fn in sorted(os.listdir(lang_dir)):
            if not fn.endswith('.tess'):
                continue
            tid = base_work(fn[:-len('.tess')])
            if tid in registry:
                present.add(tid)
                lines.append(f'texts/{lang}/{tid}.tess')
                lines.append(f'texts/{lang}/{tid}.part.*.tess')
    for tid in sorted(registry):
        if tid not in present:
            lines.append(f'# {tid}: in the registry, not yet on this checkout')
    return lines


def write_block(gitignore_path, lines):
    with open(gitignore_path, encoding='utf-8') as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        raise SystemExit(
            f'{gitignore_path} has no {BEGIN!r} / {END!r} markers to replace. '
            'Add them once by hand, then rerun this script.')
    before, rest = text.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    block = '\n'.join([BEGIN] + lines + [END])
    new_text = before + block + after
    with open(gitignore_path, 'w', encoding='utf-8') as f:
        f.write(new_text)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--root', default=os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))),
        help='Repository root (default: the repository this script lives in).')
    args = ap.parse_args()

    lines = build_lines(args.root)
    gitignore_path = os.path.join(args.root, '.gitignore')
    write_block(gitignore_path, lines)
    print(f'wrote {len(lines)} line(s) to the restricted-texts block of {gitignore_path}')


if __name__ == '__main__':
    main()
